version: '3'
services:
  backend:
    build:
      context: ./backend
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: 
      context: ./frontend/my-book-tracking-app
    command: npm run dev 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/my-book-tracking-app
    restart: always
