version: '3'
services:
  app:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: "sqlite:latest"
    container_name: my-book-database
    ports:
      - "5432:5432"
    volumes:
      - ./backend/my_book_database.db:/var/lib/sqlite/my_book_database.db

