# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set environment variables for FastAPI
ENV PYTHONUNBUFFERED 1
ENV FASTAPI_APP main:app

# Create and set the working directory
RUN mkdir /app
WORKDIR /app

# Copy the requirements file into the container
COPY ./app/requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of your application's code into the container
COPY ./app /app

# Expose port 8000 to the outside world
EXPOSE 8000

# Define the command to run your FastAPI app using Uvicorn
CMD ["uvicorn", "--host", "0.0.0.0", "--port", "8000", "main:app"]
